<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Menu;

class MenuSeeder extends Seeder
{
    public function run()
    {
        Menu::create([
            [
                'name' => 'dimsum ayam',
                'category' => 'dimsum ayam ',
                'price' => 18000,
                'description' => ' olahan daging ayam dibalut pangsit lembut',
                'image_url' => 'dimsum-ayam.jpg',
            ],
            [
                'name' => ' dimsum crabstick',
                'category' => 'dimsum ayam',
                'price' => 19000,
                'description' => ' olahan daging ayam topping crab stick',
                'image_url' => 'dimsum-crabstick.jpg',
            ],
            [
                'name' => 'nori mentaiko',
                'category' => 'dimsum ayam',
                'price' => 19000,
                'description' => 'olahan daging ayam dibalut rumput laut & topping telur ikan tobiko',
                'image_url' => 'nori-mentaiko.jpg',
            ],
            [
                'name' => 'dimsum cheese',
                'category' => 'dimsum ayam',
                'price' => 19000,
                'description' => 'olahan daging ayam dengan topping keju mozzarella',
                'image_url' => 'dimsum-cheese.jpg',
            ],
            [
                'name' => 'lumpia ayam',
                'category' => 'dimsum ayam',
                'price' => 19000,
                'description' => 'olahan daging ayam dibalut kulit tahu goreng',
                'image_url' => 'lumpia-ayam.jpg',
            ],
            [
                'name' => 'pangsit sanghai',
                'category' => 'dimsum ayam',
                'price' => 19000,
                'description' => 'pangsit ayam dengan isian sawi putih dan jahe',
                'image_url' => 'pangsit-sanghai.jpg',
            ],
            [
                'name' => 'gyoza steamed',
                'category' => 'dimsum ayam',
                'price' => 19000,
                'description' => 'dumpling isi olahan daging ayam & sayuran',
                'image_url' => 'gyoza-steamed.jpg',
            ],
            [
                'name' => 'dimsum fire',
                'category' => 'dimsum ayam',
                'price' => 20000,
                'description' => 'olahan daging ayam dengan topping extra pedas',
                'image_url' => 'dimsum-fire.jpg',
            ],
            [
                'name' => 'dimsum hot spicy',
                'category' => 'dimsum ayam',
                'price' => 19000,
                'description' => 'olahan daging ayam topping saus pedas nikmat',
                'image_url' => 'dimsum-hot-spicy.jpg',
            ],
            [
                'name' => 'dimsum jamur',
                'category' => 'dimsum ayam',
                'price' => 19000,
                'description' => 'olahan daging ayam perpanduan jamur gurih',
                'image_url' => 'dimsum-jamur.jpg',
            ],
            [
                'name' => 'dimsum bolognese',
                'category' => 'dimsum ayam',
                'price' => 19000,
                'description' => 'olahan daging ayam topping saus bolognese berempah & creamy',
                'image_url' => 'dimsum-bolognese.jpg',
            ],
            [
                'name' => 'chicken feet',
                'category' => 'dimsum ayam',
                'price' => 19000,
                'description' => ' ceker ayam dengan kuah merah khas china',
                'image_url' => 'chicken-feet.jpg',
            ],
            [
                'name' => 'xiao long bao',
                'category' => 'dimsum ayam',
                'price' => 22000,
                'description' => ' dumpling lembut dengan isian kuah gurih di dalamnya',
                'image_url' => 'xiao-long-bao.jpg',
            ],
            [
                'name' => 'dimsum mentaiko',
                'category' => 'dimsum ayam',
                'price' => 19000,
                'description' => 'olahan daging ayam dibalur pangsit & topping telur ikan tobiko',
                'image_url' => 'dimsum-mentaiko.jpg',
            ],
            [
                'name' => 'dimsum carbonara cheese',
                'category' => 'dimsum ayam',
                'price' => 20000,
                'description' => 'olahan daging ayam topping saus keju creamy & gurih',
                'image_url' => 'dimsum-carbonara-cheese.jpg',
            ],
            [
                'name' => 'pangsit chili oil',
                'category' => 'dimsum ayam',
                'price' => 20000,
                'description' => 'olahan daging ayam topping saus keju creamy dan gurih',
                'image_url' => 'pangsit-chili-oil.jpg',
            ],
            [
                'name' => 'Rambo shrimp',
                'category' => 'dimsum ayam udang',
                'price' => 18000,
                'description' => 'olahan daging udang dibalut pangsit renyah & gurih',
                'image_url' => 'Rambo-shrimp.jpg',
            ],
            [
                'name' => 'ekkado',
                'category' => 'dimsum ayam udang',
                'price' => 19000,
                'description' => 'olahan daging ayam udang dibalut kulit tahu gurih isi telur puyuh',
                'image_url' => 'ekkado.jpg',
            ],
            [
                'name' => 'udacheese',
                'category' => 'dimsum ayam udang',
                'price' => 18000,
                'description' => 'olahan daging ayam udang isian keju leleh dibalut tepung gurih',
                'image_url' => 'udacheese.jpg',
            ],
            [
                'name' => 'dimsum ayam udang',
                'category' => 'dimsum ayam udang',
                'price' => 19000,
                'description' => 'olahan daging ayam udang dibalut pangsit yang lembut',
                'image_url' => 'dimsum-ayam-udang.jpg',
            ],
            [
                'name' => 'lumpia ayam udang',
                'category' => 'dimsum ayam udang',
                'price' => 19000,
                'description' => 'olahan daging ayam udang dibalut kulit tahu gurih',
                'image_url' => 'lumpia-ayam-udang.jpg',
            ],
            [
                'name' => 'cakwe udang',
                'category' => 'dimsum ayam udang',
                'price' => 18000,
                'description' => 'olahan daging ayam udang dibalut kulit tahu gurih',
                'image_url' => 'cakwe-udang.jpg',
            ],
            [
                'name' => 'chee cheong fun',
                'category' => 'dimsum ayam udang',
                'price' => 18000,
                'description' => 'gulungan tepung beras tipis & kenyal dengan topping beragam',
                'image_url' => 'chee-cheong-fun.jpg',
            ],
            [
                'name' => 'gohyong',
                'category' => 'dimsum ayam udang',
                'price' => 25000,
                'description' => 'olahan ayam udang dibalut kulit tahu gurih & kuah segar',
                'image_url' => 'gohyong.jpg',
            ],
            [
                'name' => 'hakaw',
                'category' => 'dimsum ayam udang',
                'price' => 18000,
                'description' => 'olahan daging udang dibalut kulit lembut & kenyal',
                'image_url' => 'hakaw.jpg',
            ],
            [
                'name' => 'sup lumpia ayam udang',
                'category' => 'dimsum ayam udang',
                'price' => 18000,
                'description' => 'olahan daging ayam udang dibalut kulit tahu & kuah gurih',
                'image_url' => 'sup-lumpia-ayam-udang.jpg',
            ],
            [
                'name' => 'mie jagoan',
                'category' => 'mie',
                'price' => 15000,
                'description' => 'Mie gurih topping spesial ayam suir & pangsit goreng',
                'image_url' => 'mie-jagoan.jpg',
            ],
            [
                'name' => 'bakmie jagoan',
                'category' => 'mie',
                'price' => 18000,
                'description' => 'Mie gurih topping spesial ayam jamur dan sawi',
                'image_url' => 'bakmie-jagoan.jpg',
            ],
            [
                'name' => 'mie pangsit chili oil',
                'category' => 'mie',
                'price' => 18000,
                'description' => 'mie gepeng & pangsit ayam dipadu saus chili oil',
                'image_url' => 'mie-pangsit-chili-oil.jpg',
            ],
            [
                'name' => 'Odeng & suki mix 1',
                'category' => 'mie',
                'price' => 27000,
                'description' => 'odeng, fish cake, chikuwa long, lobster ball, dumpling & fish Roll',
                'image_url' => 'Odeng&suki-mix-1.jpg',
            ],
            [
                'name' => 'japanese beef rice bowl',
                'category' => 'nasi dan mie',
                'price' => 30000,
                'description' => 'nasi & shortplate beef US dipadu bumbu khas jepang',
                'image_url' => 'japanese-beef-rice-bowl.jpg',
            ],
            [
                'name' => 'nasi tim ayam jamur',
                'category' => 'nasi dan mie',
                'price' => 20000,
                'description' => 'nasi tim ayam jamur spesial topping telur',
                'image_url' => 'nasi-tim-ayam-jamur.jpg',
            ],
            [
                'name' => 'spicy chicken katsu curry rice',
                'category' => 'nasi dan mie',
                'price' => 30000,
                'description' => 'ayam katsu dengan kari pedas khas jepang',
                'image_url' => 'spicy-chicken-katsu-curry-rice.jpg',
            ],
            [
                'name' => 'tamago curry',
                'category' => 'nasi dan mie',
                'price' => 20000,
                'description' => 'scrambled egg lembut dengan kari khas jepang',
                'image_url' => 'tamago-curry.jpg',
            ],
            [
                'name' => 'japanese scrambled egg',
                'category' => 'nasi dan mie',
                'price' => 16000,
                'description' => 'nasi topping scrambled egg gurih dan lembut',
                'image_url' => 'japanese-scrambled-egg.jpg',
            ],
            [
                'name' => 'chicken katsu mentai rice',
                'category' => 'nasi dan mie',
                'price' => 35000,
                'description' => 'nasi dengan ayam katsu saus mentai gurih & creamy topping telur',
                'image_url' => 'chicken-katsu-mentai-rice.jpg',
            ],
            [
                'name' => 'spicy beef curry rice',
                'category' => 'nasi dan mie',
                'price' => 30000,
                'description' => 'nasi dengan shortplate beef dengan kari khas Jepang',
                'image_url' => 'spicy-beef-curry-rice.jpg',
            ],
            [
                'name' => 'udon & suki mix 2',
                'category' => 'nasi dan mie',
                'price' => 25000,
                'description' => 'mie udon, satsumage, fish tofu, fish cake, & fish roll',
                'image_url' => 'udon&suki-mix-2.jpg',
            ],
            [
                'name' => 'hakata ramen ebi furai',
                'category' => 'nasi dan mie',
                'price' => 28000,
                'description' => 'mie ramen lembut dengan kuah kaldu ayam creamy topping Ebi Furai',
                'image_url' => 'hakata-ramen-ebi-furai.jpg',
            ],
            [
                'name' => 'hakata ramen basic',
                'category' => 'nasi dan mie',
                'price' => 18000,
                'description' => 'mie ramen lembut dengan kuah kaldu ayam creamy',
                'image_url' => 'hakata-ramen-basic.jpg',
            ],
            [
                'name' => 'spicy hakata udon',
                'category' => 'nasi dan mie',
                'price' => 30000,
                'description' => 'mie ramen lembut dengan kuah kaldu ayam creamy dan pedas, topping ebi furai',
                'image_url' => 'spicy-hakata-udon.jpg',
            ],
            [
                'name' => 'beef soyu ramen',
                'category' => 'nasi dan mie',
                'price' => 28000,
                'description' => 'mie ramen lembut dengan kuah gurih khas jepang',
                'image_url' => 'beef-soyu-ramen.jpg',
            ],
            [
                'name' => 'niku udon dimsum date',
                'category' => 'nasi dan mie',
                'price' => 35000,
                'description' => 'mie udon kenyal dipadu kuah khas jepang, topping shortplate beef + kriuk (free ice tea)',
                'image_url' => 'niku-udon-dimsum-date.jpg',
            ],
            [
                'name' => 'beef curry udon',
                'category' => 'nasi dan mie',
                'price' => 35000,
                'description' => 'mie udon kenyal dipadu beef slice dengan kari pedas khas jepang (free ice tea)',
                'image_url' => 'beef-curry-udon.jpg',
            ],
            [
                'name' => 'kitsune udon dimsum date',
                'category' => 'nasi dan mie',
                'price' => 35000,
                'description' => 'mie udon kenyal dipadu kuah khas jepang, topping ayam katsu jumbo + kriuk (free ice tea)',
                'image_url' => 'kitsune-udon-dimsum-date.jpg',
            ],
            [
                'name' => 'spicy curry udon katsu',
                'category' => 'nasi dan mie',
                'price' => 35000,
                'description' => 'mie udon kenyal dipadu ayam katsu dengan kari pedas khas jepang (free ice tea)',
                'image_url' => 'spicy-curry-udon-katsu.jpg',
            ],
            [
                'name' => 'pao telur asin',
                'category' => 'camilan',
                'price' => 22000,
                'description' => 'pao isian telur asin yang manis, gurih, & creamy',
                'image_url' => 'pao-telur-asin.jpg',
            ],
            [
                'name' => 'pao coklat',
                'category' => 'camilan',
                'price' => 20000,
                'description' => 'pao isian coklat lumer',
                'image_url' => 'pao-coklat.jpg',
            ],
            [
                'name' => 'mantau choco',
                'category' => 'camilan',
                'price' => 15000,
                'description' => 'kue beragi lembut & gurih dipadu coklat manis',
                'image_url' => 'mantau-choco.jpg',
            ],
            [
                'name' => 'mantau plain',
                'category' => 'camilan',
                'price' => 15000,
                'description' => 'kue beragi lembut & gurih',
                'image_url' => 'mantau-plain.jpg',
            ],
            [
                'name' => 'onde telur asin',
                'category' => 'camilan',
                'price' => 22000,
                'description' => 'varian unik onde-onde, isian telur asin yang manis, gurih, & creamy',
                'image_url' => 'onde-telur-asin.jpg',
            ],
            [
                'name' => 'pao ayam charsiuw',
                'category' => 'camilan',
                'price' => 20000,
                'description' => 'pao isian ayam cincang bumbu merah',
                'image_url' => 'pao-ayam-charsiuw.jpg',
            ],
            [
                'name' => 'japanese milk pudding',
                'category' => 'camilan',
                'price' => 13000,
                'description' => 'puding susu khas jepang tekstur lembut & manis pas',
                'image_url' => 'japanese-milk-pudding.jpg',
            ],
            [
                'name' => 'ebi furai',
                'category' => 'camilan',
                'price' => 18000,
                'description' => 'udang lapis tepung crunchy (3 pcs)',
                'image_url' => 'ebi-furai.jpg',
            ],
            [
                'name' => 'chicken egg roll',
                'category' => 'camilan',
                'price' => 18000,
                'description' => 'telur gulung isian daging ayam (4 pcs)',
                'image_url' => 'chicken-egg-roll.jpg',
            ],
            [
                'name' => 'french fries',
                'category' => 'camilan',
                'price' => 15000,
                'description' => 'kentang goreng tekstur renyah di luar dan lembut di dalam',
                'image_url' => 'french-fries.jpg',
            ],
            [
                'name' => 'ramyeon tteokbokki',
                'category' => 'camilan',
                'price' => 28000,
                'description' => 'mie ramen kue beras kenyal dipadu saus pedas',
                'image_url' => 'ramyeon-tteokbokki.jpg',
            ],
            [
                'name' => 'tteokbokki & odeng',
                'category' => 'camilan',
                'price' => 20000,
                'description' => 'odeng dan kue beras dipadu kuah khas korea gochujang',
                'image_url' => 'tteokbokki&odeng.jpg',
            ],
            [
                'name' => 'fish roll goreng',
                'category' => 'camilan',
                'price' => 20000,
                'description' => 'gorengan bahan dasar ikan dengan bumbu khas (5 pcs)',
                'image_url' => 'fish-roll-goreng.jpg',
            ],
            [
                'name' => 'french fries & sausage',
                'category' => 'camilan',
                'price' => 20000,
                'description' => 'kentang goreng dipadu dengan cocktail beef',
                'image_url' => 'french-fries&sausage.jpg',
            ],
            [
                'name' => 'spicy chicken wing',
                'category' => 'camilan',
                'price' => 20000,
                'description' => 'sayap ayam berbumbu pedas (4 pcs)',
                'image_url' => 'spicy-chicken-wing.jpg',
            ],
            [
                'name' => 'odeng spicy gochujang',
                'category' => 'camilan',
                'price' => 28000,
                'description' => 'odeng dipadu kuah khas korea gochujang',
                'image_url' => 'odeng-spicy-gochujang.jpg',
            ],
            [
                'name' => 'lychee tea',
                'category' => 'minuman',
                'price' => 15000,
                'description' => 'minuman teh dipadu buah leci',
                'image_url' => 'lychee-tea.jpg',
            ],
            [
                'name' => 'chocolate latte',
                'category' => 'minuman',
                'price' => 15000,
                'description' => 'minuman coklat premium dipadu susu segar lembut',
                'image_url' => 'chocolate-latte.jpg',
            ],
            [
                'name' => 'es buah semangka',
                'category' => 'minuman',
                'price' => 18000,
                'description' => 'minuman segar dan creamy dipadu irisan semangka',
                'image_url' => 'es-buah-semangka.jpg',
            ],
            [
                'name' => 'es cendol',
                'category' => 'minuman',
                'price' => 18000,
                'description' => 'minuman tekstur creamy, cendol bentuk tetesan air dipadu nangka & gula aren',
                'image_url' => 'es-cendol.jpg',
            ],
            [
                'name' => 'premium thai tea',
                'category' => 'minuman',
                'price' => 18000,
                'description' => 'minuman teh susu premium rasa teh kuat & aroma rempah unik',
                'image_url' => 'premium-thai-tea.jpg',
            ],
            [
                'name' => 'premium green tea latte',
                'category' => 'minuman',
                'price' => 18000,
                'description' => 'minuman teh hijau premium dipadu susu segar lembut',
                'image_url' => 'premium-green-tea-latte.jpg',
            ],
            [
                'name' => 'taro latte',
                'category' => 'minuman',
                'price' => 15000,
                'description' => 'minuman taro/talas dipadu susu segar yang gurih, manis pas',
                'image_url' => 'taro-latte.jpg',
            ],
            [
                'name' => 'lemon tea',
                'category' => 'minuman',
                'price' => 10000,
                'description' => 'minuman segar perpaduan teh seduh & sari lemon asam',
                'image_url' => 'lemon-tea.jpg',
            ],
            [
                'name' => 'sarsaparila',
                'category' => 'minuman',
                'price' => 15000,
                'description' => 'minuman karbonasi sentuhan herbal atau "berkayu"',
                'image_url' => 'sarsaparila.jpg',
            ],
            [
                'name' => 'milk tea',
                'category' => 'minuman',
                'price' => 15000,
                'description' => 'minuman teh berkualitas dipadu susu segar lembut',
                'image_url' => 'milk-tea.jpg',
            ],
            [
                'name' => 'red velvet latte',
                'category' => 'minuman',
                'price' => 15000,
                'description' => 'minuman rasa kue red velvet sensasi lembut & manis pas',
                'image_url' => 'red-velvet-latte.jpg',
            ],
            [
                'name' => 'classic mojito mint',
                'category' => 'minuman',
                'price' => 16000,
                'description' => 'minuman jenis koktail segar perpaduan air jeruk nipis dan mint',
                'image_url' => 'classic-mojito-mint.jpg',
            ],
            [
                'name' => 'kopi aren latte',
                'category' => 'minuman',
                'price' => 18000,
                'description' => 'minuman kopi dipadu susu segar & gula aren dengan tekstur creamy',
                'image_url' => 'kopi-aren-latte.jpg',
            ],
            [
                'name' => 'ice tea',
                'category' => 'minuman',
                'price' => 8000,
                'description' => 'minuman teh dingin yang manis & segar',
                'image_url' => 'ice-tea.jpg',
            ],
            [
                'name' => 'fresh milk brown sugar',
                'category' => 'minuman',
                'price' => 15000,
                'description' => 'minuman susu segar dipadu gula aren, manis pas',
                'image_url' => 'fresh-milk-brown-sugar.jpg',
            ],
            [
                'name' => 'fam-eats dimsum',
                'category' => 'paket hemat',
                'price' => 160000,
                'description' => 'dimsum mix big, mie jagoan, nasi tim ayam jamur, ekkado, pao telur asin, 1 liter ice lemon tea',
                'image_url' => 'fam-eats-dimsum.jpg',
            ],
            [
                'name' => 'yum-yum bestie baskets',
                'category' => 'paket hemat',
                'price' => 65000,
                'description' => 'lumpia ayam/udang, spicy chicken katsu curry rice, milk tea, es buah semangka',
                'image_url' => 'yum-yum-bestie-baskets.jpg',
            ],
            [
                'name' => 'monster pack',
                'category' => 'paket hemat',
                'price' => 80000,
                'description' => 'dimsum ayam dengan topping yang bisa di mix 4 varian topping, yaitu mentai, carbonara cheese, creamy bolognese, hot spicy, & fire',
                'image_url' => 'monster-pack.jpg',
            ],
            [
                'name' => 'dimsum delight family combo',
                'category' => 'paket hemat',
                'price' => 127000,
                'description' => 'dimsum mentaiko, lumpia ayam/udang, ekkado, gyoza, dimsum mentai, sarsaparila',
                'image_url' => 'dimsum-delight-family-combo.jpg',
            ],
            [
                'name' => 'sweetheart dimsum bundle',
                'category' => 'paket hemat',
                'price' => 50000,
                'description' => 'dimsum gyoza, mie jagoan, 2 sarsaparila',
                'image_url' => 'sweetheart-dimsum-bundle.jpg',
            ],
            [
                'name' => 'dimsum date night special',
                'category' => 'paket hemat',
                'price' => 98000,
                'description' => 'dimsum mix, 2 sarsaparila',
                'image_url' => 'dimsum-date-night-special.jpg',
            ],
            [
                'name' => 'dynasty dimsum family',
                'category' => 'paket hemat',
                'price' => 118000,
                'description' => 'dimsum mix, nori mentaiko, ekkado, gyoza, chongfan, 4 ice lemon tea',
                'image_url' => 'dynasty-dimsum-family.jpg',
            ],
            [
                'name' => "bestie's bites bundle",
                'category' => 'paket hemat',
                'price' => 54000,
                'description' => 'dimsum mentaiko, gyoza, 2 sarsaparila',
                'image_url' => 'bestie\'s-bites-bundle.jpg',
            ],
            [
                'name' => 'BFF dimsum fiesta',
                'category' => 'paket hemat',
                'price' => 45000,
                'description' => 'siomay daging, ekkado, 2 ice lemon tea',
                'image_url' => 'BFF-dimsum-fiesta.jpg',
            ],

        ]);
    }
}
