<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Menu;

class MenuSeeder extends Seeder
{
    public function run()
    {
        Menu::insert([
            [
                'name' => 'dimsum ayam',
                'category' => 'dimsum ayam ',
                'price' => 18000,
                'description' => ' olahan daging ayam dibalut pangsit lembut',
                'image_url' => '',
            ],
            [
                'name' => ' dimsum crabstick',
                'category' => 'dimsum ayam',
                'price' => 19000,
                'description' => ' olahan daging ayam topping crab stick',
                'image_url' => '',
            ],
            [
                'name' => 'nori mentaiko',
                'category' => 'dimsum ayam',
                'price' => 19000,
                'description' => 'olahan daging ayam dibalut rumput laut & topping telur ikan tobiko',
                'image_url' => '',
            ],
            [
                'name' => 'dimsum cheese',
                'category' => 'dimsum ayam',
                'price' => 19000,
                'description' => 'olahan daging ayam dengan topping keju mozzarella',
                'image_url' => '',
            ],
            [
                'name' => 'lumpia ayam',
                'category' => 'dimsum ayam',
                'price' => 19000,
                'description' => 'olahan daging ayam dibalut kulit tahu goreng',
                'image_url' => '',
            ],
            [
                'name' => 'pangsit sanghai',
                'category' => 'dimsum ayam',
                'price' => 19000,
                'description' => 'pangsit ayam dengan isian sawi putih dan jahe',
                'image_url' => '',
            ],
            [
                'name' => 'gyoza steamed',
                'category' => 'dimsum ayam',
                'price' => 19000,
                'description' => 'dumpling isi olahan daging ayam & sayuran',
                'image_url' => '',
            ],
            [
                'name' => 'dimsum fire',
                'category' => 'dimsum ayam',
                'price' => 20000,
                'description' => 'olahan daging ayam dengan topping extra pedas',
                'image_url' => '',
            ],
            [
                'name' => 'dimsum hot spicy',
                'category' => 'dimsum ayam',
                'price' => 19000,
                'description' => 'olahan daging ayam topping saus pedas nikmat',
                'image_url' => '',
            ],
            [
                'name' => 'dimsum jamur',
                'category' => 'dimsum ayam',
                'price' => 19000,
                'description' => 'olahan daging ayam perpanduan jamur gurih',
                'image_url' => '',
            ],
            [
                'name' => 'dimsum bolognese',
                'category' => 'dimsum ayam',
                'price' => 19000,
                'description' => 'olahan daging ayam topping saus bolognese berempah & creamy',
                'image_url' => '',
            ],
            [
                'name' => 'chicken feet',
                'category' => 'dimsum ayam',
                'price' => 19000,
                'description' => ' ceker ayam dengan kuah merah khas china',
                'image_url' => '',
            ],
            [
                'name' => 'xiao long bao',
                'category' => 'dimsum ayam',
                'price' => 22000,
                'description' => ' dumpling lembut dengan isian kuah gurih di dalamnya',
                'image_url' => '',
            ],
            [
                'name' => 'dimsum mentaiko',
                'category' => 'dimsum ayam',
                'price' => 19000,
                'description' => 'olahan daging ayam dibalur pangsit & topping telur ikan tobiko',
                'image_url' => '',
            ],
            [
                'name' => 'dimsum carbonara cheese',
                'category' => 'dimsum ayam',
                'price' => 20000,
                'description' => 'olahan daging ayam topping saus keju creamy & gurih',
                'image_url' => '',
            ],
            [
                'name' => 'pangsit chili oil',
                'category' => 'dimsum ayam',
                'price' => 20000,
                'description' => 'olahan daging ayam topping saus keju creamy dan gurih',
                'image_url' => '',
            ],
            [
                'name' => 'Rambo shrimp',
                'category' => 'dimsum ayam udang',
                'price' => 18000,
                'description' => 'olahan daging udang dibalut pangsit renyah & gurih',
                'image_url' => '',
            ],
            [
                'name' => 'ekkado',
                'category' => 'dimsum ayam udang',
                'price' => 19000,
                'description' => 'olahan daging ayam udang dibalut kulit tahu gurih isi telur puyuh',
                'image_url' => '',
            ],
            [
                'name' => 'udacheese',
                'category' => 'dimsum ayam udang',
                'price' => 18000,
                'description' => 'olahan daging ayam udang isian keju leleh dibalut tepung gurih',
                'image_url' => '',
            ],
            [
                'name' => 'dimsum ayam udang',
                'category' => 'dimsum ayam udang',
                'price' => 19000,
                'description' => 'olahan daging ayam udang dibalut pangsit yang lembut',
                'image_url' => '',
            ],
            [
                'name' => 'lumpia ayam udang',
                'category' => 'dimsum ayam udang',
                'price' => 19000,
                'description' => 'olahan daging ayam udang dibalut kulit tahu gurih',
                'image_url' => '',
            ],
            [
                'name' => 'cakwe udang',
                'category' => 'dimsum ayam udang',
                'price' => 18000,
                'description' => 'olahan daging ayam udang dibalut kulit tahu gurih',
                'image_url' => '',
            ],
            [
                'name' => 'chee cheong fun',
                'category' => 'dimsum ayam udang',
                'price' => 18000,
                'description' => 'gulungan tepung beras tipis & kenyal dengan topping beragam',
                'image_url' => '',
            ],
            [
                'name' => 'gohyong',
                'category' => 'dimsum ayam udang',
                'price' => 25000,
                'description' => 'olahan ayam udang dibalut kulit tahu gurih & kuah segar',
                'image_url' => '',
            ],
            [
                'name' => 'hakaw',
                'category' => 'dimsum ayam udang',
                'price' => 18000,
                'description' => 'olahan daging udang dibalut kulit lembut & kenyal',
                'image_url' => '',
            ],
            [
                'name' => 'sup lumpia ayam udang',
                'category' => 'dimsum ayam udang',
                'price' => 18000,
                'description' => 'olahan daging ayam udang dibalut kulit tahu & kuah gurih',
                'image_url' => '',
            ],
            [
                'name' => 'mie jagoan',
                'category' => 'mie',
                'price' => 15000,
                'description' => 'Mie gurih topping spesial ayam suir & pangsit goreng',
                'image_url' => '',
            ],
            [
                'name' => 'bakmie jagoan',
                'category' => 'mie',
                'price' => 18000,
                'description' => 'Mie gurih topping spesial ayam jamur dan sawi',
                'image_url' => '',
            ],
            [
                'name' => 'mie pangsit chili oil',
                'category' => 'mie',
                'price' => 18000,
                'description' => 'mie gepeng & pangsit ayam dipadu saus chili oil',
                'image_url' => '',
            ],
            [
                'name' => 'Odeng & suki mix 1',
                'category' => 'mie',
                'price' => 27000,
                'description' => 'odeng, fish cake, chikuwa long, lobster ball, dumpling & fish Roll',
                'image_url' => '',
            ],
            [
                'name' => 'japanese beef rice bowl',
                'category' => 'nasi dan mie',
                'price' => 30000,
                'description' => 'nasi & shortplate beef US dipadu bumbu khas jepang',
                'image_url' => '',
            ],
            [
                'name' => 'nasi tim ayam jamur',
                'category' => 'nasi dan mie',
                'price' => 20000,
                'description' => 'nasi tim ayam jamur spesial topping telur',
                'image_url' => '',
            ],
            [
                'name' => 'spicy chicken katsu curry rice',
                'category' => 'nasi dan mie',
                'price' => 30000,
                'description' => 'ayam katsu dengan kari pedas khas jepang',
                'image_url' => '',
            ],
            [
                'name' => 'tamago curry',
                'category' => 'nasi dan mie',
                'price' => 20000,
                'description' => 'scrambled egg lembut dengan kari khas jepang',
                'image_url' => '',
            ],
            [
                'name' => 'japanese scrambled egg',
                'category' => 'nasi dan mie',
                'price' => 16000,
                'description' => 'nasi topping scrambled egg gurih dan lembut',
                'image_url' => '',
            ],
            [
                'name' => 'chicken katsu mentai rice',
                'category' => 'nasi dan mie',
                'price' => 35000,
                'description' => 'nasi dengan ayam katsu saus mentai gurih & creamy topping telur',
                'image_url' => '',
            ],
            [
                'name' => 'spicy beef curry rice',
                'category' => 'nasi dan mie',
                'price' => 30000,
                'description' => 'nasi dengan shortplate beef dengan kari khas Jepang',
                'image_url' => '',
            ],
            [
                'name' => 'udon & suki mix 2',
                'category' => 'nasi dan mie',
                'price' => 25000,
                'description' => 'mie udon, satsumage, fish tofu, fish cake, & fish roll',
                'image_url' => '',
            ],
            [
                'name' => 'hakata ramen ebi furai',
                'category' => 'nasi dan mie',
                'price' => 28000,
                'description' => 'mie ramen lembut dengan kuah kaldu ayam creamy topping Ebi Furai',
                'image_url' => '',
            ],
            [
                'name' => 'hakata ramen basic',
                'category' => 'nasi dan mie',
                'price' => 18000,
                'description' => 'mie ramen lembut dengan kuah kaldu ayam creamy',
                'image_url' => '',
            ],
            [
                'name' => 'spicy hakata udon',
                'category' => 'nasi dan mie',
                'price' => 30000,
                'description' => 'mie ramen lembut dengan kuah kaldu ayam creamy dan pedas, topping ebi furai',
                'image_url' => '',
            ],
            [
                'name' => 'beef soyu ramen',
                'category' => 'nasi dan mie',
                'price' => 28000,
                'description' => 'mie ramen lembut dengan kuah gurih khas jepang',
                'image_url' => '',
            ],
            [
                'name' => 'niku udon dimsum date',
                'category' => 'nasi dan mie',
                'price' => 35000,
                'description' => 'mie udon kenyal dipadu kuah khas jepang, topping shortplate beef + kriuk (free ice tea)',
                'image_url' => '',
            ],
            [
                'name' => 'beef curry udon',
                'category' => 'nasi dan mie',
                'price' => 35000,
                'description' => 'mie udon kenyal dipadu beef slice dengan kari pedas khas jepang (free ice tea)',
                'image_url' => '',
            ],
            [
                'name' => 'kitsune udon dimsum date',
                'category' => 'nasi dan mie',
                'price' => 35000,
                'description' => 'mie udon kenyal dipadu kuah khas jepang, topping ayam katsu jumbo + kriuk (free ice tea)',
                'image_url' => '',
            ],
            [
                'name' => 'spicy curry udon katsu',
                'category' => 'nasi dan mie',
                'price' => 35000,
                'description' => 'mie udon kenyal dipadu ayam katsu dengan kari pedas khas jepang (free ice tea)',
                'image_url' => '',
            ],
            // Tambah data lain sesuai kebutuhan
        ]);
    }
}

